### ISSUE TITLE
请教leetcode02

### ISSUE THREAD

**Issue by veryrich** [LazyboyChen7/LeetcodeStudy#1]
大佬好，我刚学习go语言，请问第二题，要如何在IDE里进行测试，因为我看函数接收值是ListNode类型，我不知道这个数据要怎么模拟传入函数😭 求指导

**Comment by LazyboyChen7** [comment]
不好意思，之前没看issues，这都两周了也不知道你解决没有。
自己测试的话就自己写两个链表，把链表头传进来就可以了，返回的也是一个链表的链表头。

**Comment by LazyboyChen7** [comment]
> 大佬好，我刚学习go语言，请问第二题，要如何在IDE里进行测试，因为我看函数接收值是ListNode类型，我不知道这个数据要怎么模拟传入函数 求指导

**Comment by LazyboyChen7** [comment]
> 大佬好，我刚学习go语言，请问第二题，要如何在IDE里进行测试，因为我看函数接收值是ListNode类型，我不知道这个数据要怎么模拟传入函数 求指导

不好意思，之前没看issues，这都两周了也不知道你解决没有。
自己测试的话就自己写两个链表，把链表头传进来就可以了，返回的也是一个链表的链表头。

**Comment by veryrich** [comment]
您好。。刚学代码我实在是没搞懂，现在也没解决，就是这个链表头不知道怎么定义也搞不懂要怎么用，您的测试代码还在嘛，可以共享一下嘛🙏太感谢了

**Comment by LazyboyChen7** [comment]
> 您好。。刚学代码我实在是没搞懂，现在也没解决，就是这个链表头不知道怎么定义也搞不懂要怎么用，您的测试代码还在嘛，可以共享一下嘛太感谢了

刚出炉的，链表头不就是一个链表节点嘛，传它就好了。
package main

import (
	"fmt"
)

type ListNode struct {
	Val int
	Next *ListNode
}

func NewList(args ...int) *ListNode {
	head := &ListNode{Val:0,Next:nil}
	re := head
	for _,num := range args {
		l := &ListNode{Val:num,Next:nil}
		re.Next = l
		re = re.Next
	}
	return head.Next
}

func addTwoNumbers(l1 *ListNode, l2 *ListNode) *ListNode {
    head := &ListNode{-1,nil}
    h:= head
    for count:=0;l1!=nil||l2!=nil||count!=0;{
        if l1!=nil{
            count+= l1.Val      
            l1 = l1.Next
        }
        if l2!=nil{
            count+= l2.Val
            l2 = l2.Next
        }
        node:= &ListNode{count%10,nil}
        head.Next = node
        head = head.Next
        count = count/10
    }
    return h.Next
}

func main() {
	l1 := NewList(2,4,5)
	l2 := NewList(3,5,6)
	l3 := addTwoNumbers(l1,l2)
	prt(l1)
	prt(l2)
	prt(l3)
}

func prt(head *ListNode) {
	re := head
	for re != nil {
		fmt.Printf("%d", re.Val)
		re = re.Next
	}
	fmt.Println()
}

**Comment by veryrich** [comment]
😭谢谢您 我好好理解一下
